Add drbd module and state. (#17)
* Remove code where old enum classes where used

After removing enum34 from shaptools the code
must be adapted for that

* Rename the RPM package from salt-saphana to salt-shaptools (#18)

* Rename package to salt-shaptools

* Adjust CI to install shaptools from SUSE Repo

* Rename RPM package files.

* Fix typo and package description.

* Change the package version to 0.1.0

* Remove used RPM variable.

* Remove python-shaptools dependency
It will be handled by the formulas as salt standard recommendation.

* Fix readme with the new project name. Fix the badges too.

* Fix typos

* Fix Typo

* Create code to manage unicast in old crm versions

* Fix bug using resource refresh

* Collect coverage only once.
To avoid errors on the codeclimate execution.

* Update changelog file

* Add drbd module and state.

* Add drbd module/state test cases.

* Modify the spec for drbd.

* Adapt spec file to work with old SLE12 versions

* Remove the dummy return value.

* Make drbd module test coverage to 100%

* Make drbd state test coverage to 100%

* Fix unicast detection method

* Add __virtual__ method to drbd module/state and mask test.

* Fix code style of drbd module/state based on review comment.

https://github.com/SUSE/salt-shaptools/pull/17

* Modify generic exception to CommandExecutionError.
Change assert from self.assert* to single assert.

* Change mock to mock_cmd
Combine patch.dict to the same block.
Mock time and sleep method in test.

* Change all assert list function to simple assert

self.assert* for list use different name in py2/py3
like:
    try:  # python2
        self.assertItemsEqual(drbd.status(), ret)
    except AttributeError:  # python3
        self.assertCountEqual(drbd.status(), ret)

* Create multiple instances for MagicMock() instead of deepcopy.

copy.deepcopy() of a MagicMock() instance only succeed in py3.
In py2:
   -> unit.states.test_drbd.DrbdStatesTestCase.test_wait_for_successful_synced
       Traceback (most recent call last):
         File "xxx/tests/unit/states/test_drbd.py", line 866,
          in test_wait_for_successful_synced
           mock_time_time = copy.deepcopy(mock_time_time_bak)
         File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
           y = _reconstruct(x, rv, 1, memo)
         ...
         File "/usr/lib64/python2.7/copy.py", line 182, in deepcopy
           rv = reductor(2)
       TypeError: can't pickle listiterator objects

* Use built-in __context__ to replace global variable.

Replace lastpnodevolumes and ret(statusret)

* Use built-in __context__ to replace global variable.

Replace resource for status().
Refer to:
https://docs.saltstack.com/en/latest/topics/development/modules/developing.html#context

* Remove the json conditions for drbdsetup.

Since only support json format of drbdsetup at the moment.