Create multiple instances for MagicMock() instead of deepcopy.
copy.deepcopy() of a MagicMock() instance only succeed in py3.
In py2:
   -> unit.states.test_drbd.DrbdStatesTestCase.test_wait_for_successful_synced
       Traceback (most recent call last):
         File "xxx/tests/unit/states/test_drbd.py", line 866,
          in test_wait_for_successful_synced
           mock_time_time = copy.deepcopy(mock_time_time_bak)
         File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
           y = _reconstruct(x, rv, 1, memo)
         ...
         File "/usr/lib64/python2.7/copy.py", line 182, in deepcopy
           rv = reductor(2)
       TypeError: can't pickle listiterator objects